// Copyright 2024 Team BH.

#pragma once

#include "CoreMinimal.h"
#include "Runtime/GameplayTags/Public/NativeGameplayTags.h"

namespace RsGameplayTags
{
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_GAME);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_GAMEMENU);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_MENU);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_MODAL);

	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_ACTION_ESCAPE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_ACTION_BACK);

	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_HPmax);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_HPcur);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_GPmax);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_GPcur);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_GPdec);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_MPmax);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_MPcur);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_EPmax);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_EPcur);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_ATK);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_IMP);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_DEF);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_CRITrate);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_CRITdmg);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_INV);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_SA);

	// SetByCaller
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MANUAL);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DURATION);
}
