// Copyright 2024 Team BH.


#include "RsGameplayTags.h"

namespace RsGameplayTags
{
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_UI_LAYER_GAME, "UI.Layer.Game", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_UI_LAYER_GAMEMENU, "UI.Layer.GameMenu", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_UI_LAYER_MENU, "UI.Layer.Menu", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_UI_LAYER_MODAL, "UI.Layer.Modal", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_ATTACK_SOURCE, "Coefficient.Attack.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_ATTACK_TARGET, "Coefficient.Attack.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_IMPACT_SOURCE, "Coefficient.Impact.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_IMPACT_TARGET, "Coefficient.Impact.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_MAXHEALTH_SOURCE, "Coefficient.MaxHealth.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_MAXHEALTH_TARGET, "Coefficient.MaxHealth.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_CURRENTHEALTH_SOURCE, "Coefficient.CurrentHealth.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_CURRENTHEALTH_TARGET, "Coefficient.CurrentHealth.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_MAXSTAGGER_SOURCE, "Coefficient.MaxStagger.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_MAXSTAGGER_TARGET, "Coefficient.MaxStagger.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_CURRENSTAGGER_SOURCE, "Coefficient.CurrentStagger.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_CURRENSTAGGER_TARGET, "Coefficient.CurrentStagger.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_CRITICALRATE_SOURCE, "Coefficient.CriticalRate.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_CRITICALRATE_TARGET, "Coefficient.CriticalRate.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_CRITICALBONUS_SOURCE, "Coefficient.CriticalBonus.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_CRITICALBONUS_TARGET, "Coefficient.CriticalBonus.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_DEFENSE_SOURCE, "Coefficient.Defense.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_DEFENSE_TARGET, "Coefficient.Defense.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_SHIELD_SOURCE, "Coefficient.Shield.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_COEFFICIENT_SHIELD_TARGET, "Coefficient.Shield.Target", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_MANUAL_MAGNITUDE, "Manual.Magnitude", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_MANUAL_DURATION, "Manual.Duration", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_MANUAL_LEVEL, "Manual.Level", "");
}