// Copyright 2024 Team BH.


#include "RsGameplayTags.h"

namespace RsGameplayTags
{
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_LAYER_GAME, "UI.Layer.Game", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_LAYER_GAMEMENU, "UI.Layer.GameMenu", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_LAYER_MENU, "UI.Layer.Menu", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_LAYER_MODAL, "UI.Layer.Modal", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_ACTION_ESCAPE, "UI.Action.Escape", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_ACTION_BACK, "UI.Action.Back", "");

	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_ATK, "Stat.ATK", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_IMP, "Stat.IMP", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_HPmax, "Stat.HPmax", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_HPcur, "Stat.HPcur", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_DEF, "Stat.DEF", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(MANUAL, "Manual", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(DURATION, "Duration", "");
}