// Copyright 2024 Team BH.


#include "RsGameplayTags.h"

namespace RsGameplayTags
{
	// UI
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_LAYER_GAME, "UI.Layer.Game", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_LAYER_GAMEMENU, "UI.Layer.GameMenu", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_LAYER_MENU, "UI.Layer.Menu", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_LAYER_MODAL, "UI.Layer.Modal", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_ACTION_ESCAPE, "UI.Action.Escape", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_ACTION_BACK, "UI.Action.Back", "");

	// Ability System
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_HPmax, "Stat.HPmax", "Max Health");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_HPcur, "Stat.HPcur", "Current Health");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_MPmax, "Stat.MPmax", "Max Mana");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_MPcur, "Stat.MPcur", "Current Mana");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_GPmax, "Stat.GPmax", "Max Stagger");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_GPcur, "Stat.GPcur", "Current Stagger");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_GPdec, "Stat.GPdec", "Stagger Decay");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_UPmax, "Stat.UPmax", "Max Ultimate");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_UPcur, "Stat.UPcur", "Current Ultimate");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_BP, "Stat.BP", "Barrier");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_ATK, "Stat.ATK", "Attack");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_IMP, "Stat.IMP", "Impact");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_DEF, "Stat.DEF", "Defense");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_CRTrate, "Stat.CRTrate", "Critical Rate");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_CRTdmg, "Stat.CRTdmg", "Critical Damage");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_MOV, "Stat.MOV", "Movement Speed");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(STAT_ATS, "Stat.ATS", "Action Speed");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_HPmax_SOURCE, "Coefficient.HPmax.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_HPmax_TARGET, "Coefficient.HPmax.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_HPcur_SOURCE, "Coefficient.HPcur.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_HPcur_TARGET, "Coefficient.HPcur.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_MPcur_SOURCE, "Coefficient.MPcur.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_MPcur_TARGET, "Coefficient.MPcur.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_BP_SOURCE, "Coefficient.BP.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_BP_TARGET, "Coefficient.BP.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_ATK_SOURCE, "Coefficient.ATK.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_ATK_TARGET, "Coefficient.ATK.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_IMP_SOURCE, "Coefficient.IMP.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_IMP_TARGET, "Coefficient.IMP.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_DEF_SOURCE, "Coefficient.DEF.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_DEF_TARGET, "Coefficient.DEF.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_ATS_SOURCE, "Coefficient.ATS.Source", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_ATS_TARGET, "Coefficient.ATS.Target", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COEFFICIENT_CONSTANT, "Coefficient.Constant", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_JUMP, "Ability.Jump", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_ATTACK_LIGHT, "Ability.Attack.Light", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_ATTACK_HEAVY, "Ability.Attack.Heavy", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_SKILL_E, "Ability.Skill.E", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_SKILL_Q, "Ability.Skill.Q", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_SKILL_R, "Ability.Skill.R", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_DODGE_PERFECT, "Ability.Dodge.Perfect", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_GUARD, "Ability.Guard", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_SPRINT, "Ability.Sprint", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_LOCKON, "Ability.LockOn", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_HITREACTION_NORMAL, "Ability.HitReaction.Normal", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_HITREACTION_KNOCKBACK, "Ability.HitReaction.KnockBack", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_GROGGY, "Ability.Groggy", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_DEATH, "Ability.Death", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_COMBO_1, "Ability.Combo.1", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_COMBO_2, "Ability.Combo.2", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_COMBO_3, "Ability.Combo.3", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_COMBO_4, "Ability.Combo.4", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ABILITY_COMBO_5, "Ability.Combo.5", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COOLDOWN_SKILL_E, "Cooldown.Skill.E", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COOLDOWN_SKILL_Q, "Cooldown.Skill.Q", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COOLDOWN_SKILL_R, "Cooldown.Skill.R", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COOLDOWN_DODGE, "Cooldown.Dodge", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COOLDOWN_GUARD, "Cooldown.Guard", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(COOLDOWN_GLOBALPARTYSWITCH, "Cooldown.GlobalPartySwitch", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(EFFECT_DAMAGE, "Effect.Damage", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(EFFECT_DAMAGE_SUPERARMORPIERCE, "Effect.Damage.SuperArmorPierce", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(EFFECT_DAMAGE_INVINCIBLEPIERCE, "Effect.Damage.InvinciblePierce", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(EFFECT_DAMAGE_FEEDBACK, "Effect.Damage.Feedback", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(EFFECT_CANNOTDECAYSTAGGER, "Effect.CannotDecayStagger", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GAMEPLAYCUE_DAMAGE_HEALTH, "GameplayCue.Damage.Health", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GAMEPLAYCUE_DAMAGE_STAGGER, "GameplayCue.Damage.Stagger", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GAMEPLAYCUE_HEALING, "GameplayCue.Healing", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GAMEPLAYCUE_BUFF, "GameplayCue.Buff", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GAMEPLAYCUE_DEBUFF, "GameplayCue.Debuff", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GAMEPLAYCUE_SPRINT, "GameplayCue.Sprint", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GAMEPLAYCUE_ATTACKSIGNAL, "GameplayCue.AttackSignal", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GAMEPLAYCUE_DEFENSE_PERFECT, "GameplayCue.Defense.Perfect", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(CHARACTER_PLAYERCONTROLLED, "Character.PlayerControlled", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(MOVEMENT_GROUNDED, "Movement.Grounded", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(MOVEMENT_FALLING, "Movement.Falling", "");
	
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ANIMNOTIFY_EVENT1, "AnimNotify.Event1", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ANIMNOTIFY_EVENT2, "AnimNotify.Event2", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ANIMNOTIFY_EVENT3, "AnimNotify.Event3", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ANIMNOTIFY_EVENT4, "AnimNotify.Event4", "");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(ANIMNOTIFY_EVENT5, "AnimNotify.Event5", "");
}