// Copyright 2024 Team BH.

#pragma once

#include "CoreMinimal.h"
#include "Runtime/GameplayTags/Public/NativeGameplayTags.h"

namespace RsGameplayTags
{
	// UI
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_GAME);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_GAMEMENU);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_MENU);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_MODAL);

	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_ACTION_ESCAPE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_ACTION_BACK);

	// Ability System
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_HPmax);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_HPcur);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_MPmax);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_MPcur);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_GPmax);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_GPcur);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_GPdec);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_UPmax);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_UPcur);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_BP);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_ATK);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_IMP);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_DEF);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_CRTrate);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_CRTdmg);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_INV);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_SUA);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_MOV);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(STAT_ATS);

	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_HPmax_SOURCE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_HPmax_TARGET);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_HPcur_SOURCE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_HPcur_TARGET);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_BP_SOURCE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_BP_TARGET);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_ATK_SOURCE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_ATK_TARGET);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_IMP_SOURCE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_IMP_TARGET);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_DEF_SOURCE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_DEF_TARGET);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_ATS_SOURCE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_ATS_TARGET)
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COEFFICIENT_CONSTANT);
	
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_JUMP);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_SPRINT);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_DODGE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_DODGE_JUST);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_ATTACK_LIGHT);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_ATTACK_HEAVY);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_SKILL_PASSIVE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_SKILL_E);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_SKILL_Q);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_SKILL_R);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_LOCKON);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_HITREACTION_NORMAL);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_HITREACTION_KNOCKBACK);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_GROGGY);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_DEATH);
	
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_COMBO1);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_COMBO2);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_COMBO3);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_COMBO4);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_COMBO5);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_ENHANCED);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ABILITY_DODGECOUNTER);
	
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COOLDOWN_SKILL_E);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COOLDOWN_SKILL_Q);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COOLDOWN_SKILL_R);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COOLDOWN_DODGE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(COOLDOWN_GLOBALPARTYSWITCH);
	
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_DAMAGE);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_DAMAGEFEEDBACK);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_CANNOTDECAYSTAGGER);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_PASSIVE1);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_PASSIVE2);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_PASSIVE3);
	
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GAMEPLAYCUE_DAMAGE_HEALTH);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GAMEPLAYCUE_DAMAGE_STAGGER);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GAMEPLAYCUE_HEALING);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GAMEPLAYCUE_BUFF);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GAMEPLAYCUE_DEBUFF);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GAMEPLAYCUE_SPRINT);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GAMEPLAYCUE_ATTACKSIGNAL);
	
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CHARACTER_PLAYERCONTROLLED);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CHARACTER_CANJUSTDODGE);
	
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MOVEMENT_GROUNDED);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MOVEMENT_FALLING);
	
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ANIMNOTIFY_EVENT1);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ANIMNOTIFY_EVENT2);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ANIMNOTIFY_EVENT3);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ANIMNOTIFY_EVENT4);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ANIMNOTIFY_EVENT5);
	RS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ANIMNOTIFY_EVENT6);
}
